[client]
showSidebarNavigation = false
[theme]
base="light"
primaryColor="#25a22f"
secondaryBackgroundColor="#cbcbcb"
textColor="#000000"
[global]
disableWidgetStateDuplicationWarning = true
showWarningOnDirectExecution = false